services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    container_name: gitlab
    ports:
      - 82:80
      - 8443:443
      - 2222:22
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.matchmates.de'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    networks:
      - npm_default

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - ./dev/urandom:/dev/random:ro
    expose:
      - 3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: mysecretpassword
      MB_DB_HOST: postgres
    networks:
      - npm_default
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    depends_on:
      - postgres

  postgres:
    image: postgres:17.6
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabaseappdb
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - metabase_postgres:/var/lib/postgresql/data
    networks:
      - npm_default

volumes:
  metabase_postgres:
  gitlab_config:
  gitlab_logs:
  gitlab_data:

networks:
  npm_default:
    external: true
